### ISSUE TITLE
Multiple exceptions

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [alexkey/getwide#1]
First I got this error
`Traceback (most recent call last):
  File "getwide.py", line 399, in <module>
    main()
  File "getwide.py", line 389, in main
    resolutions=resolutions, path=args.output)
  File "getwide.py", line 183, in __init__
    categories))
  File "c:\users\karl\appdata\local\programs\python\python36\Lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "getwide.py", line 215, in fetch_categories
    page = await self._fetcher.fetch_page(_HOST)
  File "getwide.py", line 98, in fetch_page
    with aiohttp.Timeout(self._timeout):
AttributeError: module 'aiohttp' has no attribute 'Timeout'
__main__:78: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
__main__:188: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
asyncio[14260]: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022B67825E10>`

After fixing it, I got this one

`__main__:79: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
__main__:189: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
asyncio[14100]: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D992AB6E80>
asyncio[14100]: Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001D`

**Comment by alexkey** [comment]
Hi there!
I fixed it (at) https://github.com/alexkey/getwide/commit/70e72b03cdc3c65adea174f139ddfda40945f10e
Thx
